#!/bin/bash

VERSION=`echo %{name} | sed 's/[[:alpha:]|(|[:space:]]//g' | sed 's/\-*//' | awk  -F. '{print $1 "." $2 "." $3}'`
INSTALL_PREFIX="${RPM_INSTALL_PREFIX}/ropen/${VERSION}"

echo $VERSION

if [ -f /etc/issue ] ; then
    ISSUSE=`cat /etc/issue | grep SUSE | wc -l`
    if [ ${ISSUSE} -eq 1 ] ; then
        if [ -f ${INSTALL_PREFIX}/lib64/R/lib/libreadline.so.6 ] ; then
            mv ${INSTALL_PREFIX}/lib64/R/lib/libreadline.so.6 ${INSTALL_PREFIX}/lib64/R/lib/libreadline.so.6.sav
        fi
    fi
fi
if [ "$ROPEN_KEEPPATH" != "true" ] # currently we'll noop for declines
then
    # /usr/bin/R and /usr/bin/Rscript are the entry points for R
    # On a Debian system, users might have r-base installed, which
    # provides /usr/bin/R and /usr/bin/Rscript but not as an alternative (See Bug #255040)
    #
    # Here, we move /usr/bin/R and /usr/bin/Rscript and register as
    # alternatives. It's a temporary measure that gets us closer to 
    # the ideal state of all R distros using alternatives.

    for file in R Rscript
    do
        if [ -f /usr/bin/$file ]
        then
            # If r-base is present, rename the files and install as alternative (priority: 100)
            mv /usr/bin/$file /usr/bin/$file.distrib
            update-alternatives --install /usr/bin/$file $file /usr/bin/$file.distrib 100
        fi
        # Whether r-base is present or not, honor user input and Install MRO as alternative (priority: 200)
        update-alternatives --install /usr/bin/$file $file "${INSTALL_PREFIX}/lib64/R/bin/$file" 200
    done
fi

