#!/bin/bash
VERSION=`echo $DPKG_MAINTSCRIPT_PACKAGE | sed 's/[[:alpha:]|(|[:space:]]//g' | sed 's/\-*//' | awk  -F. '{print $1 "." $2 "." $3}'`
PREFIX="/opt/microsoft/ropen/${VERSION}"

set +f

mkdir -p ${PREFIX}/lib64/R/backup/lib
mv ${PREFIX}/lib64/R/lib/*.so ${PREFIX}/lib64/R/backup/lib
cp ${PREFIX}/lib64/R/backup/lib/libR.so ${PREFIX}/lib64/R/lib
cp ${PREFIX}/stage/Linux/bin/x64/*.so ${PREFIX}/lib64/R/lib
cp ${PREFIX}/stage/Linux/bin/x64/MKL_EULA.txt ${PREFIX}/MKL_EULA.txt
