#!/bin/bash

set +f

VERSION=`echo $DPKG_MAINTSCRIPT_PACKAGE | sed 's/[[:alpha:]|(|[:space:]]//g' | sed 's/\-*//' | awk  -F. '{print $1 "." $2 "." $3}'`
INSTALL_DIR=/opt/microsoft/ropen/${VERSION}
DIRECTORY=${INSTALL_DIR}/lib64/R
if [ -e ${INSTALL_DIR}/MKL_EULA.txt ]; then
  rm ${INSTALL_DIR}/MKL_EULA.txt
fi

if [ -d "$DIRECTORY/backup" ]; then
  rm ${DIRECTORY}/lib/*.so
  mv ${DIRECTORY}/backup/lib/*.so ${DIRECTORY}/lib
fi

