#!/bin/bash

#Enable shell globbing
set +f

# We will let postinst of installing RPM take care of this if upgrade
if [[ "$1" == "1" ]]; then
    exit 0
fi

VERSION="3.5.3"
INSTALL_DIR="${RPM_INSTALL_PREFIX}/ropen/${VERSION}"
DIRECTORY="${INSTALL_DIR}/lib64/R"
if [ -e "${INSTALL_DIR}/MKL_EULA.txt" ]; then
  rm "${INSTALL_DIR}/MKL_EULA.txt"
fi
if [ -d "$DIRECTORY/backup" ]; then
  rm ${DIRECTORY}/lib/*.so
  mv ${DIRECTORY}/backup/lib/*.so ${DIRECTORY}/lib
fi
