#!/bin/bash

if [ remove = "$1" -o abort-install = "$1" -o disappear = "$1" ]
then
    for file in R Rscript
    do
      # Ensure we get rid of dead symlink
      if [[ ( -f /usr/bin/$file.distrib && -L /usr/bin/$file ) || ( ! -f /usr/bin/$file && -L /usr/bin/$file ) ]]; then
        rm /usr/bin/$file
      fi

      # Remove the diversion and restore the .distrib files
      dpkg-divert --package ${DPKG_MAINTSCRIPT_PACKAGE} --rename --remove /usr/bin/$file
    done
fi
