#!/bin/bash

VERSION=`echo $DPKG_MAINTSCRIPT_PACKAGE | sed 's/[[:alpha:]|(|[:space:]]//g' | sed 's/\-*//' | awk  -F. '{print $1 "." $2 "." $3}'`
INSTALL_PREFIX="/opt/microsoft/ropen/${VERSION}"

# We'll prompt the user for their coexistence preferences.

# /usr/bin/R and /usr/bin/Rscript are the entry points for R
# On a Debian system, users might have r-base installed, which
# provides /usr/bin/R and /usr/bin/Rscript but not as an alternative.
    
for file in R Rscript
do
   # We register a diversion, renaming the existing R and Rscript.
   # If the user upgrades via APT, new R/Rscript will be diverted.
   dpkg-divert --package ${DPKG_MAINTSCRIPT_PACKAGE} --add --rename /usr/bin/$file
done
